"""create itam schema

Revision ID: 19fa64831348
Revises: cde138860334
Create Date: 2026-07-04 10:00:18.403292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fa64831348'
down_revision: Union[str, Sequence[str], None] = 'cde138860334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_category',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_mgr_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'manager', 'it_admin', name='user_role'), server_default='employee', nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_manager_id', 'user', ['manager_id'], unique=False)
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    op.create_table('item',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_no', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('company', 'client', name='owner_type'), server_default='company', nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('available', 'assigned', 'shipping_pending', 'return_shipping_pending', 'under_repair', 'maintenance', 'lost', 'retired', 'returned_to_client', name='device_status'), server_default='available', nullable=False),
    sa.Column('current_owner_id', sa.UUID(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('qr_code_token', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['item_category.id'], ),
    sa.ForeignKeyConstraint(['current_owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code_token'),
    sa.UniqueConstraint('serial_no')
    )
    op.create_index('idx_item_available_by_category', 'item', ['category_id', 'status'], unique=False)
    op.create_index('ix_item_category_id', 'item', ['category_id'], unique=False)
    op.create_index('ix_item_current_owner_id', 'item', ['current_owner_id'], unique=False)
    op.create_index('ix_item_status', 'item', ['status'], unique=False)
    op.create_table('handover_request',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('requested_duration_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'accepted', 'rejected', 'cancelled', 'completed', name='handover_status'), server_default='requested', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_handover_request_borrower_id', 'handover_request', ['borrower_id'], unique=False)
    op.create_index('ix_handover_request_item_id', 'handover_request', ['item_id'], unique=False)
    op.create_index('ix_handover_request_owner_id', 'handover_request', ['owner_id'], unique=False)
    # Hand-added: only one accepted (active) handover per item at a time.
    op.create_index(
        'uq_one_active_handover_per_item',
        'handover_request',
        ['item_id', 'status'],
        unique=True,
        postgresql_where=sa.text("status = 'accepted'"),
    )
    op.create_table('request',
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('assigned_item_id', sa.UUID(), nullable=True),
    sa.Column('requested_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('requested', 'pending_mgr_approval', 'pending_it_approval', 'assigned', 'completed', 'rejected', 'cancelled', name='request_status'), server_default='requested', nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='request_priority'), server_default='medium', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('requires_mgr_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mgr_approval_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', name='mgr_approval_status'), server_default='not_required', nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('manager_decision_note', sa.Text(), nullable=True),
    sa.Column('manager_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('it_decided_by', sa.UUID(), nullable=True),
    sa.Column('it_decision_note', sa.Text(), nullable=True),
    sa.Column('it_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Enum('manager', 'it_admin', 'it_admin_cancel', name='rejected_by_enum'), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_wfh', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ship_tracking_url', sa.Text(), nullable=True),
    sa.Column('ship_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ship_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_tracking_url', sa.Text(), nullable=True),
    sa.Column('return_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_next_status', sa.Enum('available', 'assigned', 'shipping_pending', 'return_shipping_pending', 'under_repair', 'maintenance', 'lost', 'retired', 'returned_to_client', name='device_status'), nullable=True),
    sa.Column('is_client_direct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['item_category.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['it_decided_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_date_range', 'request', ['assigned_item_id', 'assigned_from', 'assigned_to'], unique=False)
    op.create_index('idx_request_it_queue', 'request', ['priority', 'created_at'], unique=False)
    op.create_index('ix_request_assigned_item_id', 'request', ['assigned_item_id'], unique=False)
    op.create_index('ix_request_category_id', 'request', ['category_id'], unique=False)
    op.create_index('ix_request_requester_id', 'request', ['requester_id'], unique=False)
    op.create_index('ix_request_status', 'request', ['status'], unique=False)
    # Hand-added: only one non-terminal (active) request per assigned item.
    op.create_index(
        'uq_one_active_request_per_item',
        'request',
        ['assigned_item_id', 'status'],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('rejected', 'completed', 'cancelled')"),
    )
    op.create_table('extension_request',
    sa.Column('original_request_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('current_assigned_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extended_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='extension_status'), server_default='pending', nullable=False),
    sa.Column('requires_mgr_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('mgr_approval_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', name='mgr_approval_status'), server_default='not_required', nullable=False),
    sa.Column('manager_note', sa.Text(), nullable=True),
    sa.Column('manager_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('it_decided_by', sa.UUID(), nullable=True),
    sa.Column('it_note', sa.Text(), nullable=True),
    sa.Column('it_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['it_decided_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['original_request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_request',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('update', 'damage', 'lost', name='support_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='support_status'), server_default='open', nullable=False),
    sa.Column('resolution', sa.Enum('remote_resolved', 'repaired_in_place', 'swapped', 'marked_lost', name='support_resolution'), nullable=True),
    sa.Column('it_note', sa.Text(), nullable=True),
    sa.Column('swapped_to_item_id', sa.UUID(), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['swapped_to_item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_support_open_queue', 'support_request', ['filed_at'], unique=False)
    op.create_index('ix_support_request_item_id', 'support_request', ['item_id'], unique=False)
    op.create_index('ix_support_request_request_id', 'support_request', ['request_id'], unique=False)
    op.create_index('ix_support_request_status', 'support_request', ['status'], unique=False)
    op.create_table('device_log',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('device_created', 'device_edited', 'assigned', 'client_assigned', 'ship_outbound_initiated', 'ship_outbound_completed', 'return_ship_initiated', 'return_received', 'assignment_completed', 'status_changed', 'support_opened', 'support_resolved', 'support_auto_closed', 'extension_requested', 'extension_approved', 'extension_rejected', 'handover_requested', 'handover_accepted', 'handover_rejected', 'handover_cancelled', 'handover_completed', 'marked_lost', 'retired', 'returned_to_client', 'swapped_out', 'swapped_in', name='device_log_event'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.Enum('employee', 'manager', 'it_admin', 'system', name='actor_role'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('support_request_id', sa.UUID(), nullable=True),
    sa.Column('extension_request_id', sa.UUID(), nullable=True),
    sa.Column('handover_request_id', sa.UUID(), nullable=True),
    sa.Column('from_value', sa.Text(), nullable=True),
    sa.Column('to_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_milestone', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['extension_request_id'], ['extension_request.id'], ),
    sa.ForeignKeyConstraint(['handover_request_id'], ['handover_request.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['support_request_id'], ['support_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_log_item_time', 'device_log', ['item_id', 'occurred_at'], unique=False)
    op.create_index('ix_device_log_event_type', 'device_log', ['event_type'], unique=False)
    op.create_index('ix_device_log_request_id', 'device_log', ['request_id'], unique=False)
    # Hand-added: partial index backing the device timeline view (milestone events only).
    op.create_index(
        'idx_device_log_milestones',
        'device_log',
        ['item_id', 'occurred_at'],
        unique=False,
        postgresql_where=sa.text('is_milestone = true'),
    )
    # ### end Alembic commands ###

    # Hand-added: enforce append-only device_log at the Postgres level —
    # UPDATE/DELETE become silent no-ops instead of raising or mutating rows.
    op.execute(
        "CREATE RULE device_log_no_update AS ON UPDATE TO device_log DO INSTEAD NOTHING"
    )
    op.execute(
        "CREATE RULE device_log_no_delete AS ON DELETE TO device_log DO INSTEAD NOTHING"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-added: reverse the append-only RULES and milestone index before
    # the table drop below removes the rest.
    op.execute("DROP RULE IF EXISTS device_log_no_delete ON device_log")
    op.execute("DROP RULE IF EXISTS device_log_no_update ON device_log")
    op.drop_index('idx_device_log_milestones', table_name='device_log')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_log_request_id', table_name='device_log')
    op.drop_index('ix_device_log_event_type', table_name='device_log')
    op.drop_index('idx_device_log_item_time', table_name='device_log')
    op.drop_table('device_log')
    op.drop_index('ix_support_request_status', table_name='support_request')
    op.drop_index('ix_support_request_request_id', table_name='support_request')
    op.drop_index('ix_support_request_item_id', table_name='support_request')
    op.drop_index('idx_support_open_queue', table_name='support_request')
    op.drop_table('support_request')
    op.drop_table('extension_request')
    op.drop_index('uq_one_active_request_per_item', table_name='request')
    op.drop_index('ix_request_status', table_name='request')
    op.drop_index('ix_request_requester_id', table_name='request')
    op.drop_index('ix_request_category_id', table_name='request')
    op.drop_index('ix_request_assigned_item_id', table_name='request')
    op.drop_index('idx_request_it_queue', table_name='request')
    op.drop_index('idx_request_date_range', table_name='request')
    op.drop_table('request')
    op.drop_index('uq_one_active_handover_per_item', table_name='handover_request')
    op.drop_index('ix_handover_request_owner_id', table_name='handover_request')
    op.drop_index('ix_handover_request_item_id', table_name='handover_request')
    op.drop_index('ix_handover_request_borrower_id', table_name='handover_request')
    op.drop_table('handover_request')
    op.drop_index('ix_item_status', table_name='item')
    op.drop_index('ix_item_current_owner_id', table_name='item')
    op.drop_index('ix_item_category_id', table_name='item')
    op.drop_index('idx_item_available_by_category', table_name='item')
    op.drop_table('item')
    op.drop_index('ix_user_role', table_name='user')
    op.drop_index('ix_user_manager_id', table_name='user')
    op.drop_table('user')
    op.drop_table('item_category')
    # ### end Alembic commands ###

    # Hand-added: DROP TABLE doesn't drop the Postgres ENUM types it used,
    # so autogenerate's downgrade leaves them orphaned — drop them explicitly.
    for enum_name in (
        'device_log_event',
        'actor_role',
        'rejected_by_enum',
        'mgr_approval_status',
        'request_priority',
        'request_status',
        'support_resolution',
        'support_status',
        'support_type',
        'extension_status',
        'handover_status',
        'device_status',
        'owner_type',
        'user_role',
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
